package db

import (
	"gorm.io/gorm"
)

func MigrateDatabase(db *gorm.DB) error {
	// Run v1.0.22 migration
	if err := V1_0_22_DropRetriesColumn(db); err != nil {
		return err
	}

	// Run v1.1.0 migration
	if err := V1_1_0_AddKeyHashColumn(db); err != nil {
		return err
	}

	// Run v1.2.0 migration
	if err := V1_2_0_AddModelMappingColumn(db); err != nil {
		return err
	}

	// Run v1.2.1 migration
	if err := V1_2_1_AddMappedModelColumn(db); err != nil {
		return err
	}

	// Run v1.3.0 migration
	if err := V1_3_0_AddGroupEnabledColumn(db); err != nil {
		return err
	}

	// Run v1.3.1 migration - Add dedicated group_id index for faster deletion
	if err := V1_3_1_AddGroupIDIndex(db); err != nil {
		return err
	}
	// Run v1.3.2 migration - Add slow SQL indexes (sub_group_id, groups.group_type)
	if err := V1_3_2_AddSlowSQLIndexes(db); err != nil {
		return err
	}
	// Run v1.3.3 migration - Add composite indexes for ordering and filters
	if err := V1_3_3_AddCompositeIndexes(db); err != nil {
		return err
	}
	// Run v1.4.0 migration - Add model redirect columns
	if err := V1_4_0_AddModelRedirectColumns(db); err != nil {
		return err
	}
	// Run v1.4.1 migration - Clean up auto-generated CC groups (erroneously created by old code)
	if err := V1_4_1_CleanupAutoGeneratedCCGroups(db); err != nil {
		return err
	}
	// Run v1.4.2 migration - Add composite index on groups(sort, name) for ORDER BY queries
	if err := V1_4_2_AddGroupSortNameIndex(db); err != nil {
		return err
	}
	// Run v1.5.0 migration - Add child group support (parent_group_id column)
	if err := V1_5_0_AddChildGroupSupport(db); err != nil {
		return err
	}
	// Run v1.6.0 migration - Add group-site binding support
	if err := V1_6_0_AddGroupSiteBinding(db); err != nil {
		return err
	}
	// Run v1.6.1 migration - Add timestamp index to request_logs for faster cleanup
	if err := V1_6_1_AddRequestLogsTimestampIndex(db); err != nil {
		return err
	}
	// Run v1.7.0 migration - Add site management performance indexes
	if err := V1_7_0_AddSiteManagementIndexes(db); err != nil {
		return err
	}
	// Run v1.8.0 migration - Add site opened date columns for tracking button clicks
	if err := V1_8_0_AddSiteOpenedDateColumns(db); err != nil {
		return err
	}
	// Run v1.9.0 migration - Add performance optimization indexes
	if err := V1_9_0_AddPerformanceIndexes(db); err != nil {
		return err
	}
	// Run v1.10.0 migration - Convert to many-groups-to-one-site relationship
	if err := V1_10_0_ManyGroupsToOneSite(db); err != nil {
		return err
	}
	// Run v1.11.0 migration - Add model_redirect_rules_v2 for one-to-many mapping
	if err := V1_11_0_AddModelRedirectRulesV2(db); err != nil {
		return err
	}
	// Run v1.11.1 migration - Migrate V1 redirect rules to V2 format and clear V1
	if err := V1_11_1_MigrateModelRedirectV1ToV2(db); err != nil {
		return err
	}
	// Run v1.12.0 migration - Create hub_access_keys table for centralized API management
	if err := V1_12_0_CreateHubAccessKeys(db); err != nil {
		return err
	}
	// Run v1.13.0 migration - Create Hub priority tables for priority-based routing
	if err := V1_13_0_CreateHubPriorityTables(db); err != nil {
		return err
	}
	// Run v1.14.0 migration - Add bypass_method column for Cloudflare bypass support
	return V1_14_0_AddBypassMethodColumn(db)
}

// HandleLegacyIndexes removes old indexes from previous versions to prevent migration errors
func HandleLegacyIndexes(db *gorm.DB) {
	if db.Dialector.Name() == "mysql" {
		var indexCount int64
		db.Raw(`
				SELECT COUNT(*)
				FROM information_schema.STATISTICS
				WHERE TABLE_SCHEMA = DATABASE()
				AND TABLE_NAME = 'api_keys'
				AND INDEX_NAME = 'idx_group_key'
			`).Count(&indexCount)

		if indexCount > 0 {
			db.Exec("ALTER TABLE api_keys DROP INDEX idx_group_key")
		}
		var idxApiKeysGroupKeyCount int64
		db.Raw(`
				SELECT COUNT(*)
				FROM information_schema.STATISTICS
				WHERE TABLE_SCHEMA = DATABASE()
				AND TABLE_NAME = 'api_keys'
				AND INDEX_NAME = 'idx_api_keys_group_id_key_value'
			`).Count(&idxApiKeysGroupKeyCount)

		if idxApiKeysGroupKeyCount > 0 {
			db.Exec("ALTER TABLE api_keys DROP INDEX idx_api_keys_group_id_key_value")
		}
	} else {
		db.Exec("DROP INDEX IF EXISTS idx_group_key")
		db.Exec("DROP INDEX IF EXISTS idx_api_keys_group_id_key_value")
	}
}
