package db

import (
	"gorm.io/gorm"
)

func MigrateDatabase(db *gorm.DB) error {
	// Run v1.0.22 migration
	if err := V1_0_22_DropRetriesColumn(db); err != nil {
		return err
	}

	// Run v1.1.0 migration
	if err := V1_1_0_AddKeyHashColumn(db); err != nil {
		return err
	}

	// Run v1.2.0 migration
	if err := V1_2_0_AddModelMappingColumn(db); err != nil {
		return err
	}

	// Run v1.2.1 migration
	if err := V1_2_1_AddMappedModelColumn(db); err != nil {
		return err
	}

	// Run v1.3.0 migration
	if err := V1_3_0_AddGroupEnabledColumn(db); err != nil {
		return err
	}

	// Run v1.3.1 migration - Add dedicated group_id index for faster deletion
	if err := V1_3_1_AddGroupIDIndex(db); err != nil {
		return err
	}
	// Run v1.3.2 migration - Add slow SQL indexes (sub_group_id, groups.group_type)
	if err := V1_3_2_AddSlowSQLIndexes(db); err != nil {
		return err
	}
	// Run v1.3.3 migration - Add composite indexes for ordering and filters
	if err := V1_3_3_AddCompositeIndexes(db); err != nil {
		return err
	}
	// Run v1.4.0 migration - Add model redirect columns
	if err := V1_4_0_AddModelRedirectColumns(db); err != nil {
		return err
	}
	// Run v1.4.1 migration - Clean up auto-generated CC groups (erroneously created by old code)
	if err := V1_4_1_CleanupAutoGeneratedCCGroups(db); err != nil {
		return err
	}
	// Run v1.4.2 migration - Add composite index on groups(sort, name) for ORDER BY queries
	if err := V1_4_2_AddGroupSortNameIndex(db); err != nil {
		return err
	}
	// Run v1.5.0 migration - Add child group support (parent_group_id column)
	return V1_5_0_AddChildGroupSupport(db)
}

// HandleLegacyIndexes removes old indexes from previous versions to prevent migration errors
func HandleLegacyIndexes(db *gorm.DB) {
	if db.Dialector.Name() == "mysql" {
		var indexCount int64
		db.Raw(`
				SELECT COUNT(*)
				FROM information_schema.STATISTICS
				WHERE TABLE_SCHEMA = DATABASE()
				AND TABLE_NAME = 'api_keys'
				AND INDEX_NAME = 'idx_group_key'
			`).Count(&indexCount)

		if indexCount > 0 {
			db.Exec("ALTER TABLE api_keys DROP INDEX idx_group_key")
		}
		var idxApiKeysGroupKeyCount int64
		db.Raw(`
				SELECT COUNT(*)
				FROM information_schema.STATISTICS
				WHERE TABLE_SCHEMA = DATABASE()
				AND TABLE_NAME = 'api_keys'
				AND INDEX_NAME = 'idx_api_keys_group_id_key_value'
			`).Count(&idxApiKeysGroupKeyCount)

		if idxApiKeysGroupKeyCount > 0 {
			db.Exec("ALTER TABLE api_keys DROP INDEX idx_api_keys_group_id_key_value")
		}
	} else {
		db.Exec("DROP INDEX IF EXISTS idx_group_key")
		db.Exec("DROP INDEX IF EXISTS idx_api_keys_group_id_key_value")
	}
}
