package db

import (
	"gorm.io/gorm"
)

// V1_4_1_CleanupAutoGeneratedCCGroups removes auto-generated CC groups that were erroneously
// created by old code. These groups have names ending with "-cc" and descriptions
// containing "Auto-generated OpenAI sub-group with CC support".
func V1_4_1_CleanupAutoGeneratedCCGroups(db *gorm.DB) error {
	// First, remove any sub-group relationships involving these auto-generated groups
	// to prevent foreign key constraint violations
	subQuery := db.Table("groups").
		Select("id").
		Where("description LIKE ?", "%Auto-generated OpenAI sub-group with CC support%")

	// Delete from group_sub_groups where sub_group_id matches auto-generated groups
	if err := db.Exec(`
		DELETE FROM group_sub_groups
		WHERE sub_group_id IN (
			SELECT id FROM groups
			WHERE description LIKE ?
		)
	`, "%Auto-generated OpenAI sub-group with CC support%").Error; err != nil {
		// Ignore errors - table might not exist or no rows to delete
		_ = subQuery // use the variable to avoid unused warning
	}

	// Delete the auto-generated CC groups themselves
	result := db.Exec(`
		DELETE FROM groups
		WHERE description LIKE ?
	`, "%Auto-generated OpenAI sub-group with CC support%")

	if result.Error != nil {
		// Ignore errors - just log and continue
		return nil
	}

	if result.RowsAffected > 0 {
		// Log the cleanup if any rows were deleted (using println since logrus may not be available)
		println("[Migration] Cleaned up", result.RowsAffected, "auto-generated CC groups from database")
	}

	return nil
}
