package db

import (
	"gorm.io/gorm"
)

// V1_4_1_CleanupAutoGeneratedCCGroups performs a best-effort cleanup of auto-generated CC groups
// that were erroneously created by old code. These groups have names ending with "-cc" and
// descriptions containing "Auto-generated OpenAI sub-group with CC support".
// This migration ignores errors and always succeeds to allow the system to continue functioning
// even if the cleanup fails.
func V1_4_1_CleanupAutoGeneratedCCGroups(db *gorm.DB) error {
	return db.Transaction(func(tx *gorm.DB) error {
		// First, remove any sub-group relationships involving these auto-generated groups
		// to prevent foreign key constraint violations
		if err := tx.Exec(`
			DELETE FROM group_sub_groups
			WHERE sub_group_id IN (
				SELECT id FROM groups
				WHERE description LIKE ?
			)
		`, "%Auto-generated OpenAI sub-group with CC support%").Error; err != nil {
			// Best-effort cleanup: log but do not fail migration so that the main schema
			// migration sequence is not blocked by historical data issues.
			// Note: we intentionally use println here instead of the main logger because
			// the migration layer is executed very early in process startup and logger
			// initialization may not be completed yet.
			println("[Migration] Failed to clean group_sub_groups for auto-generated CC groups:", err.Error())
		}

		// Delete the auto-generated CC groups themselves
		result := tx.Exec(`
			DELETE FROM groups
			WHERE description LIKE ?
		`, "%Auto-generated OpenAI sub-group with CC support%")

		if result.Error != nil {
			// Best-effort cleanup: log but do not fail migration to avoid blocking
			// upgrades in environments where these legacy groups cannot be deleted.
			println("[Migration] Failed to delete auto-generated CC groups:", result.Error.Error())
			return nil
		}

		if result.RowsAffected > 0 {
			// Log the cleanup if any rows were deleted
			println("[Migration] Cleaned up", result.RowsAffected, "auto-generated CC groups from database")
		}

		return nil
	})
}
