package db

import (
	"gorm.io/gorm"
)

// V1_4_1_CleanupAutoGeneratedCCGroups removes auto-generated CC groups that were erroneously
// created by old code. These groups have names ending with "-cc" and descriptions
// containing "Auto-generated OpenAI sub-group with CC support".
func V1_4_1_CleanupAutoGeneratedCCGroups(db *gorm.DB) error {
	// First, remove any sub-group relationships involving these auto-generated groups
	// to prevent foreign key constraint violations
	if err := db.Exec(`
		DELETE FROM group_sub_groups
		WHERE sub_group_id IN (
			SELECT id FROM groups
			WHERE description LIKE ?
		)
	`, "%Auto-generated OpenAI sub-group with CC support%").Error; err != nil {
		// Best-effort cleanup: log but don't fail migration
		println("[Migration] Failed to clean group_sub_groups for auto-generated CC groups:", err.Error())
	}

	// Delete the auto-generated CC groups themselves
	result := db.Exec(`
		DELETE FROM groups
		WHERE description LIKE ?
	`, "%Auto-generated OpenAI sub-group with CC support%")

	if result.Error != nil {
		println("[Migration] Failed to delete auto-generated CC groups:", result.Error.Error())
		return nil
	}

	if result.RowsAffected > 0 {
		// Log the cleanup if any rows were deleted (using println since logrus may not be available)
		println("[Migration] Cleaned up", result.RowsAffected, "auto-generated CC groups from database")
	}

	return nil
}
